### ISSUE TITLE
Readme needs updating!

### ISSUE THREAD

**Issue by katomaro** [danielmapar/HotimartBot#3]
Perhaps you should describe that Poetry is a dependency manager that will install all the dependencies for whoever is trying to run it when they execute `poetry install` and linking the documentation as an hyperlink to the name of that dependency would be better than leaving it as is.

The current sample command for running is invalid and the user is notified when trying to run it:
> poetry run hotmart-bot [domain] [username] [password]

Should become:
> poetry run hotmart-bot -usr [email] -pwd [password] [site NAME]

in order to reflect the merge changes. Also, notice the site name, as you're formating it to 
> https://{USER INPUT}.club.hotmart.com
 
When asking for the "site", one could input the whole site address resulting in something like
> https://https://example.club.hotmart.com.club.hotmart.com

You could easily implement string validation to check and fix that allowing either input to be valid.

**Comment by mpupo** [comment]
Added a PR that fix the wrong arguments problem.

**Comment by begnini** [comment]
done
